"""
Pydantic v2 models for structured query parsing and retrieval results.
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class SourceType(str, Enum):
    """Data source the user wants to search."""

    VIDEO = "video"
    PDF = "pdf"
    BOTH = "both"


class ParsedQuery(BaseModel):
    """
    Structured representation of a user's natural-language search query.

    Attributes:
        raw_query: Original query text as entered.
        semantic_topic: Core topic/subject extracted for vector search.
        speaker_name: Speaker name if the user mentioned one (e.g. "Ali").
        has_visual_intent: True if query implies visual / slide search.
        source_type: Whether to search videos, PDFs, or both.
    """

    raw_query: str = Field(..., description="Original user query")
    semantic_topic: str = Field(..., description="Cleaned topic for embedding")
    speaker_name: Optional[str] = Field(default=None, description="Extracted speaker filter")
    has_visual_intent: bool = Field(
        default=False,
        description="True when query uses visual keywords (slide, graph, chart, show, image, …)",
    )
    source_type: SourceType = Field(default=SourceType.BOTH)


class ChunkType(str, Enum):
    """Distinguishes video vs PDF chunks in results."""

    VIDEO = "video"
    PDF = "pdf"


class RetrievedResult(BaseModel):
    """
    A single retrieval result returned by the retriever.

    Attributes:
        chunk_id: UUID of the matched chunk.
        chunk_type: VIDEO or PDF.
        score: Similarity score from Qdrant (0–1 range, higher = better).
        video_id: Set for VIDEO chunks.
        pdf_id: Set for PDF chunks.
        time_start: Start timestamp (VIDEO only).
        time_end: End timestamp (VIDEO only).
        page_number: Page number (PDF only).
        speaker_name: Speaker name (VIDEO only).
        transcript_text: Speech text (VIDEO only).
        text_layer: PDF native text (PDF only).
        ocr_text: OCR content.
        caption_text: BLIP caption.
        image_path: Path to keyframe / slide image.
        youtube_url: YouTube URL for embedding the player (VIDEO only).
        pdf_title: Human-readable PDF title (PDF only).
    """

    chunk_id: str
    chunk_type: ChunkType
    score: float = Field(..., ge=0.0, le=1.0)

    # Video fields
    video_id: Optional[str] = None
    time_start: Optional[float] = None
    time_end: Optional[float] = None
    speaker_name: Optional[str] = None
    transcript_text: Optional[str] = None
    youtube_url: Optional[str] = None

    # PDF fields
    pdf_id: Optional[str] = None
    page_number: Optional[int] = None
    text_layer: Optional[str] = None
    pdf_title: Optional[str] = None

    # Shared
    ocr_text: Optional[str] = None
    caption_text: Optional[str] = None
    image_path: Optional[str] = None


class Citation(BaseModel):
    """A single source citation inside an RAGAnswer."""

    chunk_id: str
    chunk_type: ChunkType
    label: str = Field(..., description="Human-readable citation label, e.g. '0:42 – Ali'")


class RAGAnswer(BaseModel):
    """
    Structured result returned by the RAG engine.

    Attributes:
        answer: Natural-language answer generated by the LLM.
        citations: List of source citations backing the answer.
    """

    answer: str = Field(..., description="LLM-generated answer")
    citations: List[Citation] = Field(default_factory=list)
